<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net4.8</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Version>1.4.3</Version>
    <BuildNumber Condition="'$(BuildNumber)' == ''">$([System.DateTime]::UtcNow.ToString("yyDDD"))</BuildNumber>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).$(BuildNumber)</FileVersion>
    <InformationalVersion>$(Version)+b$(BuildNumber)</InformationalVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Resources/icon.ico</ApplicationIcon>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Resources/icon.ico" />
    <Content Remove="Resources/icon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/icon.ico" />
    <EmbeddedResource Include="Resources/icon.png" />
  </ItemGroup>

</Project>
